columnsTest = c('integer',
            'integer',
            'integer',
            'integer',
            'integer',
            'integer',
            'integer',
            'integer',
            'integer',
            'integer',
            'factor',
            'integer',
            'integer',
            'integer',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor',
            'factor')
original_test = read.csv('test.csv', colClasses=columnsTest)
str(original_test)

files = split(original_test, c(1:200) )
lapply(names(files), function(x){write.table(files[[x]], file = paste("testfiles/test_file-", x, '.csv', sep = ""), sep=', ',row.names=FALSE)})

